version: 0.2

phases:
  install:
    runtime-versions:
      java: 17
    commands:
      - echo Installing Maven
      - apt-get update && apt-get install -y maven
  pre_build:
    commands:
      - echo Pre-build phase
      - mvn --version
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - target/*.jar
  discard-paths: yes
